from enum import Enum


class GameStates(Enum):
    PLAYERS_TURN = 1
    ENEMY_TURN = 2
    PLAYER_DEAD = 3
    SHOW_INVENTORY = 4
    DROP_INVENTORY = 5
    TARGETING = 6
    LEVEL_UP = 7
    CHARACTER_SCREEN = 8
    CHARACTER_CREATION = 9
    GENDER_SELECTION = 10
    JOB_SELECTION = 11
    SHOW_SKILL_MENU = 13
    SKILL_TARGETING = 13
    ATTACK_MENU = 14
    TALK_TARGETING = 15
    QUEST_MENU = 16
    GIVE_INVENTORY = 17
    GIVE_TARGETING = 18
    BEE_QUEST_COMPLETED = 19
    APPLY_ITEM = 20
